FROM node:15.14-alpine3.11

ENV APP_NAME        "ecom_ts"

# installing base microservice
RUN echo "Installing global dependencies" \
  && npm install -g  typescript \
  && npm install -g ts-node-dev

WORKDIR /app
COPY . .

RUN apk update && apk upgrade \
  && apk add --no-cache git \
  && apk --no-cache add --virtual builds-deps build-base python 

RUN rm -rf node_modules  || true                  \
  && npm i

CMD  ["npm", "run", "dev"]